version: "3.7"

services:
  find-peers:
    container_name: find-peers
    restart: unless-stopped
    image: ghcr.io/jeeneeuhs/find-peers:latest
    volumes:
      - $HOME/find-peers/database:/app/database
    env_file: ./env/.env
    environment:
      - PORT=8080
    ports:
      - 80:8080
      # - 8080:8080
